### ISSUE TITLE
Increase decrease buttons working on glass panel?

### ISSUE THREAD

**Issue by lukecorkill** [daaf84/Tasmota-dimmer-switch#1]
Hi. 
I've got the dimmer working using this - so thanks for writing it up.  
I have full control through Tasmota, but can't adjust the dimmer level using the glass panel (power button works).     Should those buttons work?  If so, perhaps I've been sent a slightly different version from AliExpress.

Luke.

**Comment by lukecorkill** [comment]
Closed - realise I just need to hold buttons for longer

**Comment by ponchor17** [comment]
@lukecorkill i was on the same boat as you. and I just tried holding the buttons longer and they worked, as you said, lol
